### PR TITLE
fix(validators): print filename on error

### LINKED ISSUE #5: Print the filename that failed validation
### Enhancement Proposal

It would be handy if cos-tool printed the filename of the file that failed validation when used e.g. like so:
```
find . -path '*/prometheus_alert_rules/*' -type f -exec ./cos-tool-amd64 --format promql lint {} +
```
Currently, the output from cos-tool looks like this:
```
error validating: yaml: unmarshal errors:
  line 1: field alert not found in type rulefmt.RuleGroups
  line 2: field expr not found in type rulefmt.RuleGroups
  line 3: field for not found in type rulefmt.RuleGroups
  line 4: field labels not found in type rulefmt.RuleGroups
  line 6: field annotations not found in type rulefmt.RuleGroups
failed
```
so it's impossible to know which file failed validation.

Related: https://github.com/canonical/observability/pull/22

### PR DESCRIPTION
**Pull request by simskij**
resolves #5 

## Issue

As described in #5 

## Solution

Print filename whenever a file fails validation.

## Testing Instructions

Try the tool against the provided test data

## Release Notes

Print the filename of alert rules that fail cos-tool rule validation.

### CODE REVIEW

File: pkg/tool/common.go [hunk 1]
```diff
@@ -27,8 +27,8 @@ type LogQL struct {
 
 type Checker interface {
 	Transform(arg string, matchers *map[string]string) (string, error)
-	ValidateRules(data []byte) (*rulefmt.RuleGroups, error)
-	ValidateConfig(filename string) (error)
+	ValidateRules(filename string, data []byte) (*rulefmt.RuleGroups, error)
```
Comment (dstathis) [inline pkg/tool/common.go:30]: Seems a bit redundant to pass the name of the file *and* it's contents. Could we just read the file inside this function?

**Review by dstathis — APPROVED** [review]

File: pkg/tool/common.go (hunk 1 above)
Comment (simskij) [reply pkg/tool/common.go:30]: im torn as i also see the benefit of having a function named `ValidateSomething` not have the side-effect of also having disk IO, but on the other hand i don't think it matters much.
